### PR TITLE
Osx arm64

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
osxarm64: 
```
CMake Error at /Users/runner/miniforge3/conda-bld/pivy_1657479386200/_build_env/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Interpreter) (found version "2.7.16")
```

@conda-forge/core any ideas?

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
Thanks @jaimergp

**Comment by jaimergp** [comment]
My pleasure!

**Pull request merged**
